### ListMode: The mode that the list below will operate in
#   * Blacklist = Items added to the list will not be stackable
#   * Whitelist = Items added to the list will be stackable, but unstackable items will stay unstackable if they're not in the list
#
### Items: Items that will or will not be stacked to 64 based on the list mode above
#
### Language: The default language for in game text. If the specified language is not supported English will be used.
# Supported Languages:
#   * en_us - English
#   * zh_cn - 简体中文 (Simplified Chinese)
# Note: Language is also based off of per-player, the language specified in this config only applies
# to the console.
#
### Item Amounts: Set the amount of items that an item of that type can hold.
# Note: Items in item amounts must also be in the items list if in whitelist mode
#
ListMode: Blacklist
Items:
  - 'Example Item'
Language: en_us
Item Amounts:
  Example Item: 32